[template]
src   = "sensu_checks.json.tmpl"
dest  = "/etc/sensu/conf.d/checks.json"
owner = "root"
group = "root"
mode  = "0644"
keys = [
  "/sensu/checks",
]
reload_cmd = "supervisorctl restart sensu-server"
